name: Fetch CDN URL Every 2 Minutes

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  fetch-cdn-url:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch playlist and extract CDN URL only
        run: |
          curl -v "https://star-sports-2-hindi-hd.joker-verse.workers.dev/index.m3u8" 2>&1 \
            | grep -i '< location:' \
            | head -n 1 \
            | sed 's/< location: //I' > get.txt

      - name: Commit and push get.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add get.txt
          git commit -m "Update get.txt - $(date -u)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
