name: Fetch HDNEA Token Every 2 Minutes

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  fetch-hdnea-token:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch __hdnea__ token
        run: |
          curl -s -L "https://star-sports-2-hindi-hd.joker-verse.workers.dev/index.m3u8" \
          | grep -o '__hdnea__=[^&"]*' \
          | head -n 1 > fetch.txt

      - name: Commit and push fetch.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add fetch.txt
          git diff --cached --quiet || git commit -m "Update fetch.txt - $(date -u)" && git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
