name: Fetch Jio Playlist Every 2 Minutes

on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  fetch-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch playlist with curl verbose
        run: |
          curl -v "https://star-sports-2-hindi-hd.joker-verse.workers.dev/index.m3u8" > get.txt 2>&1

      - name: Commit and push get.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add get.txt
          git commit -m "Update get.txt - $(date -u)"
          git push
        env:
          # Use GitHub token for permission to push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
